"""initial tables

Revision ID: 82a242206ce4
Revises: 
Create Date: 2026-07-30 17:21:14.900684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a242206ce4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_merchant_name'), 'merchants', ['merchant_name'], unique=True)
    op.create_table('balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_balance_non_negative'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'currency', name='uq_merchant_currency')
    )
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_merchant_id', sa.UUID(), nullable=False),
    sa.Column('to_merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('idempotency_key', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'WAIT_PAYMENT', 'DONE', name='transferstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['to_merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_idempotency_key'), 'transfers', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_idempotency_key'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_table('balances')
    op.drop_index(op.f('ix_merchants_merchant_name'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
